Remove ParamSpec
Ovsyanka83/cached_classproperty pull request #4
Opened 2023-10-31 22:32 UTC by Atry

ParamSpec is unnecessary because the number of arguments is fixed.

2023-11-01 07:49 UTC, zmievsa requested changes
Very true! Thank you for this PR!

Could you also update the  minor version in pyproject.toml?

2024-04-10 18:11 UTC, Atry commented
Version updated

2024-04-15 04:22 UTC, zmievsa requested changes
Thanks for your work. Added a few comments.

2024-04-15 04:22 UTC, zmievsa commented on pyproject.toml
> +version = "1.1.1"
```suggestion
version = "1.1.0"
```

2024-04-15 04:22 UTC, zmievsa commented on cached_classproperty/__init__.py
> +        func: Callable[[type], T], attrname: Optional[str] = None
```suggestion
        func: Callable[[Any], T], attrname: Optional[str] = None
```

2024-04-15 04:22 UTC, zmievsa commented on cached_classproperty/__init__.py
> -    P = ParamSpec("P")
Can you please  remove the import of ParamSpec above?

2024-04-19 17:57 UTC, Atry commented
@zmievsa Any other issues?

2024-04-19 18:17 UTC, zmievsa commented
I will check again soon :pray:

2025-05-05 05:50 UTC, Atry commented
@zmievsa any update?

2025-05-17 18:32 UTC, zmievsa-semasoftware approved these changes

2025-05-17 18:33 UTC, merged

2025-05-17 18:33 UTC, zmievsa commented
@Atry apologies for the wait: life came in the way. It's done now! Releasing in a minor version right now

2025-05-17 20:46 UTC, Atry commented
No worries!

On Sat, May 17, 2025 at 11:34 Stanislav Zmiev ***@***.***>
wrote:

> *zmievsa* left a comment (zmievsa/cached_classproperty#4)
> <https://github.com/zmievsa/cached_classproperty/pull/4#issuecomment-2888529729>
>
> @Atry <https://github.com/Atry> apologies for the wait: life came in the
> way. It's done now! Releasing in a minor version right now
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/zmievsa/cached_classproperty/pull/4#issuecomment-2888529729>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AAES3OWDVRI6RFS46U4YRD32656KZAVCNFSM6AAAAAB4NZGRYSVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMZDQOBYGUZDSNZSHE>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>